const $ = id => document.getElementById(id);
const field = $('field'), fctx = field.getContext('2d');
const simplex = $('simplex'), sctx = simplex.getContext('2d');
const historyCanvas = $('history'), hctx = historyCanvas.getContext('2d');
let payload=null, traderPayload=null, sim=[], running=true, seed=42, phase=0, fragility=0, equityRange='all';
const colors={trend:'#49a9f8',chop:'#f0ad3b',stress:'#f06464',green:'#42d08c'};

function fit(canvas){const d=devicePixelRatio||1,r=canvas.getBoundingClientRect();if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}return {w:r.width,h:r.height,d};}
function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
function gaussian(){return Math.sqrt(-2*Math.log(Math.max(rand(),1e-9)))*Math.cos(6.283*rand());}
function resample(){if(!payload)return;seed=(seed+7919)>>>0;const s=payload.snapshot,N=+$('paths').value,T=+$('horizon').value,stress=+$('shock').value/100;const hist=payload.history.slice(-192);let rr=hist.map(x=>x.return).filter(Number.isFinite),mean=rr.reduce((a,b)=>a+b,0)/rr.length,sigma=Math.sqrt(rr.reduce((a,b)=>a+(b-mean)**2,0)/rr.length)||.0003;let dir=s.direction==='BULLISH'?1:-1,drift=dir*sigma*.07*s.trend_probability;sim=[];for(let n=0;n<N;n++){let p=s.price,path=[p];for(let t=0;t<T;t++){let shock=gaussian();if(rand()<.018)shock*=3.2;p*=Math.exp(drift+sigma*stress*(1+1.5*s.stress_probability)*shock);path.push(p);}sim.push(path);}let adverse=sim.filter(path=>dir>0?Math.min(...path)<s.price*(1-2*sigma*Math.sqrt(T)):Math.max(...path)>s.price*(1+2*sigma*Math.sqrt(T))).length;fragility=adverse/Math.max(sim.length,1);updateDecision();updateDecisionFactors();}
function quantile(vals,q){vals=vals.slice().sort((a,b)=>a-b);return vals[Math.floor(q*(vals.length-1))];}
function drawField(){let {w,h,d}=fit(field);fctx.setTransform(d,0,0,d,0,0);fctx.clearRect(0,0,w,h);if(!payload||!sim.length)return;let all=sim.flat(),lo=quantile(all,.01),hi=quantile(all,.99),T=sim[0].length-1;const X=t=>24+(w-48)*t/T,Y=p=>80+(h-145)*(hi-p)/(hi-lo);fctx.strokeStyle='#182129';fctx.lineWidth=1;for(let i=0;i<6;i++){let y=90+i*(h-165)/5;fctx.beginPath();fctx.moveTo(0,y);fctx.lineTo(w,y);fctx.stroke();}for(let i=0;i<Math.min(sim.length,160);i++){let path=sim[i],alpha=.035+.055*(i%7===0),end=Math.min(T,Math.floor(T*(.25+.75*((phase*.005+i*.013)%1))));fctx.strokeStyle=`rgba(73,169,248,${alpha})`;fctx.beginPath();for(let t=0;t<=end;t++){let x=X(t),y=Y(path[t]);t?fctx.lineTo(x,y):fctx.moveTo(x,y);}fctx.stroke();if(i<40){fctx.fillStyle='rgba(66,208,140,.5)';fctx.beginPath();fctx.arc(X(end),Y(path[end]),1.4,0,6.283);fctx.fill();}}let med=[];for(let t=0;t<=T;t++)med.push(quantile(sim.map(p=>p[t]),.5));fctx.strokeStyle='#eef3f5';fctx.lineWidth=2.4;fctx.beginPath();med.forEach((p,t)=>t?fctx.lineTo(X(t),Y(p)):fctx.moveTo(X(t),Y(p)));fctx.stroke();phase++;}
function drawSimplex(){let {w,h,d}=fit(simplex);sctx.setTransform(d,0,0,d,0,0);sctx.clearRect(0,0,w,h);let A=[w/2,22],B=[25,h-33],C=[w-25,h-33];sctx.strokeStyle='#34424d';sctx.lineWidth=1.5;sctx.beginPath();sctx.moveTo(...A);sctx.lineTo(...B);sctx.lineTo(...C);sctx.closePath();sctx.stroke();[['TREND',A,colors.trend],['CHOP',B,colors.chop],['STRESS',C,colors.stress]].forEach(([t,p,c])=>{sctx.fillStyle=c;sctx.font='10px ui-monospace';sctx.textAlign=p===B?'left':p===C?'right':'center';sctx.fillText(t,p[0],p[1]+(p===A?-7:18));});if(!payload)return;let s=payload.snapshot,total=s.trend_probability+s.chop_probability+s.stress_probability,pt=[(A[0]*s.trend_probability+B[0]*s.chop_probability+C[0]*s.stress_probability)/total,(A[1]*s.trend_probability+B[1]*s.chop_probability+C[1]*s.stress_probability)/total];for(let i=24;i>0;i--){sctx.fillStyle=`rgba(66,208,140,${.005*(25-i)})`;sctx.beginPath();sctx.arc(pt[0],pt[1],i,0,6.283);sctx.fill();}sctx.fillStyle='#f4f7f8';sctx.beginPath();sctx.arc(pt[0],pt[1],5,0,6.283);sctx.fill();}
function drawHistory(){let {w,h,d}=fit(historyCanvas);hctx.setTransform(d,0,0,d,0,0);hctx.clearRect(0,0,w,h);if(!payload)return;let a=payload.history.slice(-220),pad=24,lo=Math.min(...a.map(x=>x.low)),hi=Math.max(...a.map(x=>x.high)),X=i=>pad+(w-2*pad)*i/(a.length-1),Y=p=>18+(h-45)*(hi-p)/(hi-lo);hctx.strokeStyle='#1d2830';for(let i=0;i<5;i++){let y=20+i*(h-50)/4;hctx.beginPath();hctx.moveTo(0,y);hctx.lineTo(w,y);hctx.stroke();}hctx.strokeStyle='#e6ecef';hctx.lineWidth=1.4;hctx.beginPath();a.forEach((x,i)=>i?hctx.lineTo(X(i),Y(x.close)):hctx.moveTo(X(i),Y(x.close)));hctx.stroke();[['trend_probability',colors.trend],['chop_probability',colors.chop],['stress_probability',colors.stress]].forEach(([key,c],j)=>{hctx.strokeStyle=c;hctx.lineWidth=1;hctx.beginPath();a.forEach((x,i)=>{let y=h-8-28*x[key]-j*31;i?hctx.lineTo(X(i),y):hctx.moveTo(X(i),y)});hctx.stroke();});}
function pct(x){return `${Math.round(100*x)}%`;}
function setCheck(id,status,text){$(id+'Check').className=status;$(id+'Text').textContent=text;}
function updateDecision(){if(!payload)return;let s=payload.snapshot,live=!!payload.live,regimeGood=s.trend_probability>=.55&&s.stress_probability<.55,aligned=s.direction_probability>=.62,fragile=fragility>=.35||s.stress_probability>=.6;let posture='REDUCED',cls='reduced',line='Mixed evidence favors selective participation at reduced size.';if(!live){posture='OBSERVE ONLY';cls='aside';line=payload.demo?'Synthetic inputs demonstrate the interface. No current-market posture is issued.':'The feed is not live. No current-market posture is issued.';}else if(fragile){posture='STAND ASIDE';cls='aside';line='Stress or simulated adverse excursions exceed the operating threshold.';}else if(regimeGood&&aligned&&s.risk_multiplier>=.7){posture='NORMAL';cls='normal';line=`${s.direction} direction and trend state agree with contained tail stress.`;}else if(s.chop_probability>=.55){line='Chop probability is elevated; continuation signals have weak structural support.';}$('posture').textContent=posture;$('posture').className=`posture ${cls}`;$('postureLine').textContent=line;setCheck('feed',live?'pass':'fail',payload.demo?'DEMO':live?'LIVE':'STALE');setCheck('regime',regimeGood?'pass':s.stress_probability>=.6?'fail':'warn',s.state);setCheck('alignment',aligned?'pass':'warn',`${s.direction} ${pct(s.direction_probability)}`);setCheck('fragility',fragile?'fail':fragility>=.22?'warn':'pass',pct(fragility));$('modelExposure').textContent=posture==='OBSERVE ONLY'||posture==='STAND ASIDE'?'0%':pct(s.risk_multiplier);$('decisionBias').textContent=`BIAS ${s.direction} · ${+$('horizon').value} BARS · SHOCK ${(+ $('shock').value/100).toFixed(1)}×`;$('decisionTime').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}
function money(v,digits=0){return `${v<0?'−':''}$${Math.abs(v).toLocaleString(undefined,{minimumFractionDigits:digits,maximumFractionDigits:digits})}`;}
function drawEquity(){if(!traderPayload)return;let canvas=$('equity'),{w,h,d}=fit(canvas),ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);let all=traderPayload.equity,a=equityRange==='all'?all:all.slice(-Number(equityRange)),pad={l:24,r:52,t:18,b:46},eq=a.map(x=>x.equity),lo=Math.min(...eq),hi=Math.max(...eq),X=i=>pad.l+(w-pad.l-pad.r)*i/Math.max(a.length-1,1),Y=v=>pad.t+(h-pad.t-pad.b-62)*(hi-v)/Math.max(hi-lo,1);ctx.strokeStyle='#1d2830';ctx.lineWidth=1;for(let i=0;i<5;i++){let y=pad.t+i*(h-pad.t-pad.b-62)/4;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();ctx.fillStyle='#63727d';ctx.font='9px ui-monospace';ctx.textAlign='right';ctx.fillText(money(hi-i*(hi-lo)/4),w-5,y+3);}ctx.strokeStyle='#42d08c';ctx.lineWidth=2;ctx.beginPath();a.forEach((x,i)=>i?ctx.lineTo(X(i),Y(x.equity)):ctx.moveTo(X(i),Y(x.equity)));ctx.stroke();let ddTop=h-65;ctx.fillStyle='rgba(240,100,100,.24)';ctx.beginPath();ctx.moveTo(X(0),h-pad.b);a.forEach((x,i)=>ctx.lineTo(X(i),ddTop+52*Math.abs(x.drawdown)));ctx.lineTo(X(a.length-1),h-pad.b);ctx.closePath();ctx.fill();ctx.fillStyle='#71818d';ctx.textAlign='left';ctx.fillText('DRAWDOWN',pad.l,h-16);canvas.onmousemove=e=>{let r=canvas.getBoundingClientRect(),i=Math.max(0,Math.min(a.length-1,Math.round((e.clientX-r.left-pad.l)/(w-pad.l-pad.r)*(a.length-1)))),x=a[i],tip=$('equityTip');tip.style.display='block';tip.style.left=`${Math.min(e.clientX-r.left+12,w-150)}px`;tip.style.top=`${Math.max(e.clientY-r.top-50,75)}px`;tip.textContent=`${x.time.slice(0,10)}  ${money(x.equity)}  DD ${pct(Math.abs(x.drawdown))}`;};canvas.onmouseleave=()=>$('equityTip').style.display='none';}
function drawDistribution(){if(!traderPayload)return;let canvas=$('distribution'),{w,h,d}=fit(canvas),ctx=canvas.getContext('2d'),a=traderPayload.all_trade_pnl,bins=22,lo=Math.min(...a),hi=Math.max(...a),step=(hi-lo)/bins,count=Array(bins).fill(0);a.forEach(v=>count[Math.min(bins-1,Math.floor((v-lo)/step))]++);ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);let max=Math.max(...count),bw=(w-20)/bins;count.forEach((n,i)=>{let x=10+i*bw,y=h-22-(h-45)*n/max,center=lo+(i+.5)*step;ctx.fillStyle=center>=0?'rgba(66,208,140,.72)':'rgba(240,100,100,.72)';ctx.fillRect(x,y,Math.max(bw-2,1),h-22-y)});let zero=10+(w-20)*(0-lo)/(hi-lo);ctx.strokeStyle='#dbe2e6';ctx.beginPath();ctx.moveTo(zero,10);ctx.lineTo(zero,h-18);ctx.stroke();}
function factorRow(name,value,color,detail){return `<div class="factor-row"><span>${name}</span><i><b style="width:${Math.min(100,Math.abs(value)*100)}%;background:${color}"></b></i><strong>${detail}</strong></div>`;}
function updateTrader(){if(!traderPayload)return;let s=traderPayload.stats,b=traderPayload.best_trade,w=traderPayload.worst_trade;$('strategySource').textContent=traderPayload.demo?'SYNTHETIC LEDGER':traderPayload.live?'LIVE TRADINGVIEW':'LOCAL SNAPSHOT';$('strategySource').className=`source-pill ${traderPayload.live?'':'snapshot'}`;$('netPnl').textContent=money(s.net_profit);$('netPnl').style.color=s.net_profit>=0?colors.green:colors.stress;$('netReturn').textContent=`${(100*s.net_profit_percent).toFixed(2)}% return`;$('profitFactor').textContent=s.profit_factor.toFixed(3);$('winRate').textContent=pct(s.win_rate);$('maxDrawdown').textContent=money(-s.max_drawdown);$('maxDrawdownPct').textContent=pct(s.max_drawdown_percent);$('expectancy').textContent=money(s.expectancy);$('sharpe').textContent=s.sharpe==null?'—':s.sharpe.toFixed(2);$('avgWin').textContent=money(s.avg_win);$('avgLoss').textContent=money(s.avg_loss);$('payoff').textContent=`${s.payoff_ratio.toFixed(2)}×`;$('bestPnl').textContent=money(b.pnl);$('bestMeta').textContent=`${b.sleeve} · ${b.direction} · ${b.exit_time.slice(0,10)}`;$('bestExcursion').textContent=`RUN-UP ${money(b.runup)} · DRAW-DOWN ${money(-b.drawdown)} · ${b.bars ?? "—"} BARS`;$('worstPnl').textContent=money(w.pnl);$('worstMeta').textContent=`${w.sleeve} · ${w.direction} · ${w.exit_time.slice(0,10)}`;$('worstExcursion').textContent=`RUN-UP ${money(w.runup)} · DRAW-DOWN ${money(-w.drawdown)} · ${w.bars ?? "—"} BARS`;$('streaks').textContent=`${s.max_win_streak} / ${s.max_loss_streak}`;$('currentStreak').textContent=`CURRENT ${s.current_streak>=0?'WIN':'LOSS'} STREAK ${Math.abs(s.current_streak)}`;$('commission').textContent=money(s.commission);$('recovery').textContent=`RECOVERY FACTOR ${s.recovery_factor.toFixed(2)}× · AVG HOLD ${s.avg_bars.toFixed(1)} BARS`;$('tradeCount').textContent=`${s.trades} CLOSED · ${s.wins} W / ${s.losses} L`;$('sleeveRows').innerHTML=traderPayload.sleeves.map(x=>`<div class="sleeve-row"><span>${x.name}</span><i><b style="width:${Math.min(100,Math.abs(x.pnl)/Math.max(...traderPayload.sleeves.map(y=>Math.abs(y.pnl)))*100)}%;background:${x.pnl>=0?colors.green:colors.stress}"></b></i><strong>${money(x.pnl)} · ${pct(x.win_rate)}</strong></div>`).join('');$('tradeRows').innerHTML=traderPayload.recent_trades.map(x=>`<tr><td>${x.number}</td><td>${x.exit_time.slice(0,16).replace('T',' ')}</td><td>${x.sleeve}</td><td>${x.direction}</td><td>${x.entry_price.toFixed(2)}</td><td>${x.exit_price.toFixed(2)}</td><td>${x.bars ?? "—"}</td><td>${money(x.runup)}</td><td>${money(-x.drawdown)}</td><td class="${x.pnl>=0?'positive':'negative'}">${money(x.pnl)}</td></tr>`).join('');drawEquity();drawDistribution();updateDecisionFactors();}
function updateDecisionFactors(){if(!payload)return;let s=payload.snapshot,items=[['Trend support',s.trend_probability,colors.trend,pct(s.trend_probability)],['Directional confidence',s.direction_probability,colors.green,pct(s.direction_probability)],['Chop penalty',s.chop_probability,colors.chop,`−${pct(.15*s.chop_probability)}`],['Stress penalty',s.stress_probability,colors.stress,`−${pct(.65*s.stress_probability)}`],['Simulated fragility',fragility,fragility>.35?colors.stress:colors.green,pct(fragility)]];$('decisionFactors').innerHTML=items.map(x=>factorRow(...x)).join('');}
function updateUI(){let s=payload.snapshot;$('instrumentLabel').textContent=`${payload.symbol} / LAST CLOSED`;$('demoNotice').textContent=payload.demo?'SYNTHETIC DEMO · Artificial bars and illustrative trade ledger. Not C11 performance. Regime scores are uncalibrated.':'Research illustration · Regime scores are uncalibrated; simulated paths are scenarios.';$('price').textContent=s.price.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});$('direction').textContent=s.direction;$('direction').style.color=s.direction==='BULLISH'?colors.green:colors.stress;$('stateName').textContent=s.state;$('stateName').style.color=colors[s.state.toLowerCase()];$('posterior').textContent=`max score = ${pct(s.confidence)}`;[['trend',s.trend_probability],['chop',s.chop_probability],['stress',s.stress_probability]].forEach(([n,v])=>{$(`${n}Value`).textContent=pct(v);$(`${n}Bar`).style.width=pct(v)});$('directionProbability').textContent=pct(s.direction_probability);$('directionLabel').textContent=s.direction;$('volatility').textContent=pct(s.volatility_percentile);$('exposure').textContent=pct(s.risk_multiplier);$('confidence').textContent=pct(s.confidence);$('timestamp').textContent=`CLOSED ${s.timestamp}`;let fs=$('feedState');fs.className=`feed ${payload.live?'live':'degraded'}`;fs.querySelector('b').textContent=payload.demo?'SYNTHETIC DEMO':payload.live?'LIVE':'SNAPSHOT';fs.querySelector('small').textContent=payload.source;updateDecision();}
async function poll(){try{let r=await fetch(document.documentElement.dataset.liveUrl || '/api/live',{cache:'no-store'});payload=await r.json();if(!payload.ok)throw Error(payload.error);updateUI();resample();drawSimplex();drawHistory();}catch(e){let fs=$('feedState');fs.className='feed offline';fs.querySelector('b').textContent='OFFLINE';fs.querySelector('small').textContent=e.message;}}
async function pollTrader(){try{let r=await fetch(document.documentElement.dataset.traderUrl || '/api/trader',{cache:'no-store'});traderPayload=await r.json();if(!traderPayload.ok)throw Error('strategy report unavailable');updateTrader();}catch(e){$('strategySource').textContent='REPORT OFFLINE';$('strategySource').className='source-pill snapshot';}}
['horizon','paths','shock'].forEach(id=>$(id).addEventListener('input',()=>{$(`${id}Out`).textContent=id==='horizon'?`${$(id).value} bars`:id==='shock'?`${(+$(id).value/100).toFixed(1)}×`:$(id).value;resample();}));
$('play').onclick=()=>{running=!running;$('play').textContent=running?'Ⅱ':'▶';$('play').setAttribute('aria-label',running?'Pause animation':'Resume animation');};$('resample').onclick=resample;
document.querySelectorAll('.range-control button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.range-control button').forEach(x=>x.classList.remove('active'));button.classList.add('active');equityRange=button.dataset.range;drawEquity();});
function loop(){if(running)drawField();requestAnimationFrame(loop);}window.addEventListener('resize',()=>{drawSimplex();drawHistory();drawEquity();drawDistribution();});poll();setInterval(poll,15000);loop();
pollTrader();setInterval(pollTrader,60000);
