#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

import pandas as pd
from scipy.signal import find_peaks

ROOT = Path(__file__).resolve().parents[1]


def load_bars(path):
    payload = json.loads(Path(path).read_text())
    bars = payload.get("bars")
    if bars is None:
        result = payload.get("result", {})
        bars = result.get("bars") if isinstance(result, dict) else result
    df = pd.DataFrame(bars)
    df["datetime"] = pd.to_datetime(df["time"], unit="s", utc=True)
    return df.set_index("datetime").sort_index()[["open", "high", "low", "close", "volume"]].astype(float)


def pine_ts(ts):
    return f'timestamp("GMT+0", {ts.year}, {ts.month}, {ts.day}, {ts.hour}, {ts.minute})'


def array_block(name, timestamps, width=8):
    parts = [pine_ts(ts.to_pydatetime()) for ts in timestamps]
    lines = []
    for i in range(0, len(parts), width):
        suffix = "," if i + width < len(parts) else ""
        lines.append("    " + ", ".join(parts[i:i + width]) + suffix)
    return f"var int[] {name} = array.from(\\n" + "\\n".join(lines) + "\\n)"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default=ROOT / "tmp/tv_es1_15m_loaded_full_raw.json")
    parser.add_argument("--prominence-pct", type=float, default=1.0)
    parser.add_argument("--distance", type=int, default=5)
    parser.add_argument("--out", type=Path, default=ROOT / "pine_strategies/JD_ES_15m_SciPy_Truth_Markers_20260519.pine")
    parser.add_argument("--manifest", type=Path, default=ROOT / "reports/es_15m_scipy_truth_markers_20260519.json")
    args = parser.parse_args()

    df = load_bars(args.data)
    prominence = df["close"].median() * args.prominence_pct / 100.0
    peak_idx, _ = find_peaks(df["high"].to_numpy(float), prominence=prominence, distance=args.distance)
    valley_idx, _ = find_peaks(-df["low"].to_numpy(float), prominence=prominence, distance=args.distance)
    peak_times = df.index[peak_idx]
    valley_times = df.index[valley_idx]

    source = f"""//@version=6
indicator("JD ES 15m SciPy Truth Markers 20260519", overlay=true, max_labels_count=500)

// Generated by scripts/generate_es_scipy_truth_markers_pine.py
// Exact hindsight labels from scipy.signal.find_peaks on exported TradingView ES1! 15m data.
// Data coverage: {df.index.min().isoformat()} to {df.index.max().isoformat()}
// Method: price highs/lows, prominence_pct={args.prominence_pct}, distance={args.distance}, absolute prominence={prominence:.6f}.
// These are diagnostic labels only; they are not tradable real-time signals.

showPeaks = input.bool(true, "Show SciPy peaks")
showValleys = input.bool(true, "Show SciPy valleys")

{array_block("peakTimes", peak_times)}

{array_block("valleyTimes", valley_times)}

isPeak = showPeaks and array.includes(peakTimes, time)
isValley = showValleys and array.includes(valleyTimes, time)

plotshape(isValley, "SciPy true valley", shape.circle, location.belowbar, color=color.new(color.lime, 0), size=size.tiny, text="V")
plotshape(isPeak, "SciPy true peak", shape.circle, location.abovebar, color=color.new(color.red, 0), size=size.tiny, text="P")
"""
    args.out.write_text(source)
    args.manifest.write_text(json.dumps({
        "data": str(args.data),
        "coverage_start": df.index.min().isoformat(),
        "coverage_end": df.index.max().isoformat(),
        "prominence_pct": args.prominence_pct,
        "distance": args.distance,
        "absolute_prominence": prominence,
        "peaks": len(peak_times),
        "valleys": len(valley_times),
        "pine": str(args.out),
    }, indent=2))
    print(args.out)
    print(args.manifest)


if __name__ == "__main__":
    main()
