#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

import pandas as pd
from scipy.signal import find_peaks

from optimize_15m_mtf_reversal import load_json


ROOT = Path(__file__).resolve().parents[1]


def load_many(paths):
    frames = []
    for path in paths:
        if not path.exists():
            continue
        frames.append(load_json(path))
    if not frames:
        raise FileNotFoundError("No input data files found")
    df = pd.concat(frames).sort_index()
    df = df[~df.index.duplicated(keep="last")]
    return df


def detect(df, prominence_pct, distance):
    avg_price = df["close"].mean()
    threshold = avg_price * (prominence_pct / 100.0)
    peaks, _ = find_peaks(df["high"].to_numpy(float), prominence=threshold, distance=distance)
    valleys, _ = find_peaks(-df["low"].to_numpy(float), prominence=threshold, distance=distance)
    return df.index[peaks], df.index[valleys], threshold


def pine_ts(ts):
    return f'timestamp("GMT+0", {ts.year}, {ts.month}, {ts.day}, {ts.hour}, {ts.minute})'


def chunked(items, size=8):
    for i in range(0, len(items), size):
        yield items[i : i + size]


def array_literal(name, timestamps):
    if len(timestamps) == 0:
        return f"var int[] {name} = array.new_int()\n"
    lines = [f"var int[] {name} = array.from("]
    parts = [pine_ts(ts.to_pydatetime()) for ts in timestamps]
    for chunk in chunked(parts):
        line = "    " + ", ".join(chunk)
        if chunk[-1] != parts[-1]:
            line += ","
        lines.append(line)
    lines.append(")")
    return "\n".join(lines) + "\n"


def render(peaks, valleys, prominence_pct, distance, threshold, data_start, data_end):
    return f'''//@version=6
indicator("JD CL 15m SciPy Truth Markers 20260519", overlay=true, max_labels_count=500)

// Generated by scripts/generate_cl_scipy_truth_markers_pine.py
// Exact hindsight labels from scipy.signal.find_peaks on exported TradingView CL1! 15m data.
// Data coverage: {data_start.isoformat()} to {data_end.isoformat()}
// Method: price highs/lows, prominence_pct={prominence_pct}, distance={distance}, absolute prominence={threshold:.6f}.
// These are diagnostic labels only; they are not tradable real-time signals.

showPeaks = input.bool(true, "Show SciPy peaks")
showValleys = input.bool(true, "Show SciPy valleys")

{array_literal("peakTimes", peaks)}
{array_literal("valleyTimes", valleys)}
isPeak = showPeaks and array.includes(peakTimes, time)
isValley = showValleys and array.includes(valleyTimes, time)

plotshape(isValley, "SciPy true valley", shape.circle, location.belowbar, color=color.new(color.lime, 0), size=size.tiny, text="V")
plotshape(isPeak, "SciPy true peak", shape.circle, location.abovebar, color=color.new(color.red, 0), size=size.tiny, text="P")
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", nargs="+", type=Path, default=[
        ROOT / "tmp/tv_cl1_15m_loaded_full_raw.json",
        ROOT / "tmp/tv_cl1_15m_last500_20260519.json",
    ])
    parser.add_argument("--prominence-pct", type=float, default=1.0)
    parser.add_argument("--distance", type=int, default=5)
    parser.add_argument("--out", type=Path, default=ROOT / "pine_strategies/JD_CL_15m_SciPy_Truth_Markers_20260519.pine")
    parser.add_argument("--manifest", type=Path, default=ROOT / "reports/cl_15m_scipy_truth_markers_20260519.json")
    args = parser.parse_args()

    df = load_many(args.data)
    peaks, valleys, threshold = detect(df, args.prominence_pct, args.distance)
    args.out.write_text(render(peaks, valleys, args.prominence_pct, args.distance, threshold, df.index.min(), df.index.max()))
    args.manifest.write_text(json.dumps({
        "data_files": [str(p) for p in args.data],
        "data_start": df.index.min().isoformat(),
        "data_end": df.index.max().isoformat(),
        "prominence_pct": args.prominence_pct,
        "distance": args.distance,
        "absolute_prominence": threshold,
        "peaks": len(peaks),
        "valleys": len(valleys),
        "out": str(args.out),
    }, indent=2))
    print(args.out)
    print(args.manifest)
    print(f"peaks={len(peaks)} valleys={len(valleys)}")


if __name__ == "__main__":
    main()
